
package com.v2soft.ws.example.employeeforhr;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-09-04T16:37:02.465+05:30
 * Generated source version: 3.3.2
 *
 */

public class EmployeeForHr_EmployeeForHrPort_Server{

    protected EmployeeForHr_EmployeeForHrPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new EmployeeForHrPortImpl();
        String address = "http://localhost:8080/EmployeeForHr";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new EmployeeForHr_EmployeeForHrPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
