package com.v2soft.training.model;
// Generated Oct 15, 2019 10:20:54 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * EmployeeLogin generated by hbm2java
 */
@Entity
@Table(name = "employee_login", catalog = "employee")
public class EmployeeLogin implements java.io.Serializable {

	private String username;
	private Employee employeeInfo;
	private String password;
	private Set<LoginSession> loginSessions = new HashSet<LoginSession>(0);

	public EmployeeLogin() {
	}

	public EmployeeLogin(String username, Employee employeeInfo, String password) {
		this.username = username;
		this.employeeInfo = employeeInfo;
		this.password = password;
	}

	public EmployeeLogin(String username, Employee employeeInfo, String password, Set<LoginSession> loginSessions) {
		this.username = username;
		this.employeeInfo = employeeInfo;
		this.password = password;
		this.loginSessions = loginSessions;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_id", nullable = false)
	@JsonIgnore
	public Employee getEmployee() {
		return this.employeeInfo;
	}

	public void setEmployee(Employee employeeInfo) {
		this.employeeInfo = employeeInfo;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeeLogin")
	@JsonIgnore
	public Set<LoginSession> getLoginSessions() {
		return this.loginSessions;
	}

	public void setLoginSessions(Set<LoginSession> loginSessions) {
		this.loginSessions = loginSessions;
	}

}
