package com.v2soft.training.model;
// Generated Oct 15, 2019 10:20:54 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LoginSessionId generated by hbm2java
 */
@Embeddable
public class LoginSessionId implements java.io.Serializable {

	private String username;
	private int loginStatus;

	public LoginSessionId() {
	}

	public LoginSessionId(String username, int loginStatus) {
		this.username = username;
		this.loginStatus = loginStatus;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "login_status", nullable = false)
	public int getLoginStatus() {
		return this.loginStatus;
	}

	public void setLoginStatus(int loginStatus) {
		this.loginStatus = loginStatus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LoginSessionId))
			return false;
		LoginSessionId castOther = (LoginSessionId) other;

		return ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
				&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& (this.getLoginStatus() == castOther.getLoginStatus());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + this.getLoginStatus();
		return result;
	}

}
